window.__ModuleLoader__.load({ id: 'dsh-cite', factory: require => {
  const React = require('react'), { useState, useEffect, useRef } = React, h = React.createElement, route = 'api/dsh-cite/library';
  let activeLang = 'zh', cache = { kind: 'doi', text: '', label: '', preview: null, chosen: [], selected: [], style: 'gb-t-7714', dirty: false, job: null };
  const css = `.dcw{font:14px/1.65 system-ui,sans-serif;color:var(--fg,#203b42);min-width:0;padding:8px}.dcw *{box-sizing:border-box}.dcw h2{font-size:23px;margin:0}.dcw h3{font-size:17px;margin:0 0 10px}.dcw p{margin:8px 0}.dcw .muted{color:var(--fg-muted,#677881);font-size:13px}.dcw .bar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0}.dcw button,.dcw .button{font:inherit;color:inherit;border:1px solid var(--border,#c5d5d4);border-radius:8px;padding:8px 12px;background:var(--bg-surface,#fff);text-decoration:none;cursor:pointer;white-space:normal}.dcw button.primary{background:#27695b;border-color:#27695b;color:white}.dcw button:disabled{opacity:.45;cursor:default}.dcw label{display:block;margin:10px 0 4px}.dcw input:not([type=checkbox]),.dcw textarea,.dcw select{font:inherit;color:inherit;width:100%;border:1px solid var(--border,#bfd1d0);border-radius:8px;background:var(--bg,#fff);padding:9px}.dcw input[type=checkbox]{accent-color:#27695b;width:18px;height:18px;flex-shrink:0}.dcw textarea{resize:vertical;min-height:140px}.dcw .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.dcw .card{border:1px solid var(--border,#c5d5d4);border-radius:12px;padding:14px;margin:12px 0;min-width:0;background:var(--bg-surface,#fff)}.dcw .notice{border-radius:8px;padding:10px;background:#eef5ed;color:#2a604a;overflow-wrap:anywhere}.dcw .error{background:#fff0ea;color:#943b27}.dcw .entry{padding:12px 0;border-top:1px solid var(--border,#d3dedd);overflow-wrap:anywhere}.dcw .entry:first-child{border-top:0}.dcw .choose{display:flex;align-items:flex-start;gap:10px;margin:0;cursor:pointer}.dcw .choose input{margin-top:4px}.dcw .choose>span{min-width:0}.dcw .tag{display:inline-block;margin:4px 5px 0 0;padding:2px 6px;border-radius:5px;font-size:12px;background:var(--bg-muted,#edf2f1)}.dcw .warn{color:#a65318}.dcw pre{font:13px/1.6 system-ui,sans-serif;white-space:pre-wrap;overflow-wrap:anywhere;max-height:220px;overflow:auto;margin:8px 0}.dcw details{margin-top:10px}.dcw summary{cursor:pointer}.dcw dl{display:grid;grid-template-columns:auto 1fr;gap:5px 14px}.dcw dt{font-weight:600}.dcw dd{margin:0;overflow-wrap:anywhere}.dcw progress{width:100%;height:12px}.dcw :focus-visible{outline:3px solid #79cdb4;outline-offset:2px}[role=dialog]:has(.dcw){width:min(1200px,calc(100vw - 40px))!important;max-width:1200px!important}@media(max-width:800px){.dcw{padding:3px}.dcw .grid{grid-template-columns:1fr}[role=dialog]:has(.dcw){width:100%!important;max-width:100%!important;flex-direction:column!important}[role=dialog]:has(.dcw)>nav+div{min-width:0;width:100%}[role=dialog]:has(.dcw)>nav+div>div:has(.dcw){padding:12px!important;min-width:0}[role=dialog]:has(.dcw) nav{width:100%!important;flex-basis:auto!important;border-right:0;max-height:170px;overflow:auto}[role=dialog]:has(.dcw) nav>div:has(>button){display:flex;flex-direction:row!important;flex-wrap:wrap;gap:4px}}`;
  async function api(body) {
    const r = await fetch(new URL(route, document.baseURI), { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json', 'x-dsh-cite': '1' }, body: JSON.stringify(body) });
    let data; try { data = await r.json() } catch { throw new Error(activeLang === 'en' ? 'Could not read the library response. Check whether DSH restarted, then retry.' : '无法读取文献库响应，请检查 DSH 是否已重启。') }
    if (!r.ok || !data.ok) { const e = new Error(activeLang === 'en' ? data.messageEn || 'The operation could not be completed. Check the input or refresh and retry.' : data.message || '操作未完成'); e.status = r.status; throw e; } return data.value;
  }
  function download(kind, style, lang, ids) { const u = new URL(route, document.baseURI); u.searchParams.set('kind', kind); if (style) u.searchParams.set('style', style); if (lang) u.searchParams.set('lang', lang); if (ids?.length) u.searchParams.set('ids', ids.join(',')); return u.href; }
  const authors = work => work.authors.map(a => a.name || [a.family, a.given].filter(Boolean).join(' ')).join(', ');
  const valueText = v => Array.isArray(v) ? v.map(a => typeof a === 'object' ? a.name || [a.family, a.given].filter(Boolean).join(' ') : String(a)).join(', ') : String(v ?? '');
  function Workbench({ locale }) {
    const [lang, setLang] = useState('zh'), [kind, setKind] = useState(cache.kind), [text, setText] = useState(cache.text), [label, setLabel] = useState(cache.label);
    const [preview, setPreview] = useState(cache.preview), [chosen, setChosen] = useState(cache.chosen), [selected, setSelected] = useState(cache.selected), [style, setStyle] = useState(cache.style), [dirty, setDirty] = useState(cache.dirty);
    const [library, setLibrary] = useState({ revision: 0, entries: [], sources: [] }), [job, setJob] = useState(cache.job), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [conflict, setConflict] = useState(false), [search, setSearch] = useState(''), [limit, setLimit] = useState(50), [activeId, setActiveId] = useState(''), [citation, setCitation] = useState('');
    const busyRef = useRef(false), fileRef = useRef(null), dirtyRef = useRef(dirty); dirtyRef.current = dirty;
    const t = (zh, en) => lang === 'en' ? en : zh, running = job?.state === 'running', locked = busy || running;
    const warning = code => ({ missing_title: t('缺少标题', 'Missing title'), missing_authors: t('缺少作者', 'Missing authors'), missing_year: t('缺少年份', 'Missing year'), missing_doi: t('没有 DOI，无法在线补全', 'No DOI for online lookup'), long_citation_key: t('引用键过长，导出将使用短键', 'Long citation key; export uses a shorter key') }[code] || code);
    const fieldName = key => ({ title: t('标题', 'Title'), authors: t('作者', 'Authors'), year: t('年份', 'Year'), containerTitle: t('期刊 / 文集', 'Journal / collection'), publisher: t('出版社', 'Publisher'), type: t('文献类型', 'Type'), volume: t('卷', 'Volume'), issue: t('期', 'Issue'), page: t('页码', 'Pages'), language: t('语言', 'Language'), url: 'URL', isbn: 'ISBN' }[key] || key);
    useEffect(() => { const update = () => { activeLang = String(locale?.getSnapshot?.().active || '').startsWith('en') ? 'en' : 'zh'; setLang(activeLang); }; update(); return locale?.subscribe?.(update); }, [locale]);
    useEffect(() => { cache = { kind, text, label, preview, chosen, selected, style, dirty, job }; }, [kind, text, label, preview, chosen, selected, style, dirty, job]);
    useEffect(() => { const warn = e => { if (dirtyRef.current) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, []);
    async function refresh() { const state = await api({ action: 'list' }); setLibrary(state); setSelected(old => old.filter(id => state.entries.some(e => e.id === id))); setJob(old => state.jobs.find(j => j.id === old?.id) || state.jobs.find(j => j.state === 'running') || state.jobs.at(-1) || null); }
    useEffect(() => { refresh().catch(e => setError(e.message)); }, []);
    useEffect(() => {
      if (!running) return; let live = true, polling = false;
      const timer = setInterval(async () => { if (polling) return; polling = true; try { const next = await api({ action: 'job', job: job.id }); if (!live) return; if (next.state !== 'running') { await refresh(); if (live) setJob(next); } else setJob(next); } catch (e) { if (live) { setError(e.message); setJob(null); } } finally { polling = false; } }, 1000);
      return () => { live = false; clearInterval(timer); };
    }, [job?.id, running]);
    const referenceId = activeId && library.entries.some(e => e.id === activeId) ? activeId : library.entries[0]?.id;
    useEffect(() => { let live = true; setCitation(''); if (referenceId) api({ action: 'export', kind: 'references', ids: [referenceId], style, lang }).then(v => { if (live) setCitation(v.content) }).catch(e => { if (live) setCitation(e.message) }); return () => { live = false; }; }, [referenceId, style, lang, library.revision]);
    async function perform(fn) { if (busyRef.current) return; busyRef.current = true; setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e.message); if (e.status === 409) setConflict(true); } finally { busyRef.current = false; setBusy(false); } }
    function changeInput(set, value) { set(value); setDirty(true); setPreview(null); setChosen([]); setConflict(false); }
    async function parse() { const p = await api({ action: 'preview', kind, text, label }); setPreview(p); setChosen(p.rows.filter(r => r.selectedDefault).map(r => r.index)); setConflict(false); }
    async function save() { const oldIds = new Set(library.entries.map(e => e.id)), state = await api({ action: 'import', preview: preview.id, selection: chosen }); setLibrary(state); setSelected(state.entries.filter(e => !oldIds.has(e.id)).map(e => e.id)); setPreview(null); setChosen([]); setDirty(false); setConflict(false); setNotice(t('已保存 ' + chosen.length + ' 条。原始输入也已保留在完整备份中。', 'Saved entries: ' + chosen.length + '. Original input is preserved in the full backup.')); }
    async function upload() { const file = fileRef.current?.files?.[0]; if (!file) return; await perform(async () => { if (!/\.bib$/i.test(file.name)) throw new Error(t('请选择 .bib 文件。', 'Choose a .bib file.')); if (file.size > 256 * 1024) throw new Error(t('文件超过 256 KiB，请拆分导入。', 'File exceeds 256 KiB. Split it before importing.')); const content = await file.text(); setKind('bibtex'); setText(content); setLabel(file.name); setPreview(null); setChosen([]); setDirty(true); setConflict(false); setNotice(t('文件已读取，点击“本地预览”检查后再保存。', 'File loaded. Choose Local preview before saving.')); }); fileRef.current.value = ''; }
    function toggle(values, value, set) { set(values.includes(value) ? values.filter(v => v !== value) : [...values, value]); }
    const filtered = library.entries.filter(e => [e.work.title, authors(e.work), e.work.doi, e.work.year].join(' ').toLowerCase().includes(search.toLowerCase())), visible = filtered.slice(0, limit), selectedIds = selected.length ? selected : undefined;
    const downloadLink = (format, zh, en) => library.entries.length ? h('a', { className: 'button', href: download(format, style, lang, format === 'backup' ? undefined : selectedIds), download: '' }, t(zh, en)) : h('button', { disabled: true }, t(zh, en));
    return h('section', { className: 'dcw', 'aria-label': t('文献工作台', 'Citation workbench') }, h('style', null, css),
      h('h2', null, 'Cite'), h('p', { className: 'muted' }, t('先在本地整理文献；只有点击在线补全才会查询 Crossref。不会捏造缺失信息。', 'Organize references locally. Crossref is contacted only when you request online enrichment. Missing information is never invented.')),
      error && h('div', { className: 'notice error', role: 'alert' }, error), notice && h('div', { className: 'notice', role: 'status' }, notice),
      conflict && h('div', { className: 'notice error' }, h('p', null, t('库已在别处更新。当前输入仍保留，请重新预览再保存。', 'The library changed elsewhere. Your input is retained; preview again before saving.')), h('button', { disabled: locked || !text.trim(), onClick: () => perform(async () => { await refresh(); await parse(); }) }, t('重新预览当前输入', 'Preview current input again'))),
      h('div', { className: 'grid' }, h('div', null,
        h('div', { className: 'card' }, h('h3', null, t('1. 导入与本地预览', '1. Import and local preview')),
          h('label', { htmlFor: 'cite-kind' }, t('输入类型', 'Input type')), h('select', { id: 'cite-kind', value: kind, disabled: locked, onChange: e => changeInput(setKind, e.target.value) }, h('option', { value: 'doi' }, t('DOI 列表（每行一条）', 'DOI list (one per line)')), h('option', { value: 'bibtex' }, 'BibTeX / BibLaTeX')),
          h('label', { htmlFor: 'cite-input' }, t('DOI / BibTeX 输入', 'DOI / BibTeX input')), h('textarea', { id: 'cite-input', rows: 8, value: text, disabled: locked, spellCheck: false, onChange: e => changeInput(setText, e.target.value), placeholder: kind === 'doi' ? '10.1038/nature12345\nhttps://doi.org/10.1145/3368089.3409749' : '@article{key,\n  title={Your title},\n  author={Family, Given},\n  year={2026}\n}' }),
          h('label', { htmlFor: 'cite-source' }, t('来源名称（可选）', 'Source name (optional)')), h('input', { id: 'cite-source', value: label, maxLength: 160, disabled: locked, onChange: e => changeInput(setLabel, e.target.value) }),
          h('input', { ref: fileRef, type: 'file', accept: '.bib', style: { display: 'none' }, onChange: upload }), h('div', { className: 'bar' }, h('button', { disabled: locked, onClick: () => fileRef.current.click() }, t('上传 .bib', 'Upload .bib')), h('button', { className: 'primary', disabled: locked || !text.trim(), onClick: () => perform(parse) }, t('本地预览', 'Local preview'))),
          h('p', { className: 'muted' }, t('最多 256 KiB / 100 条；库最多 500 条。预览、去重和格式切换都不联网。上传仅读取文件，不改写原文件。', 'Up to 256 KiB / 100 entries per import; 500 in the library. Preview, deduplication and formatting are offline. Upload reads your file without changing it.')), dirty && h('p', { className: 'muted' }, t('当前输入尚未保存到文献库。关闭设置后输入仍保留。', 'Current input has not been saved. It is retained when you close settings.'))),
        preview && h('div', { className: 'card' }, h('h3', null, t('预览：选择要保存的文献', 'Preview: choose entries to save')), h('p', { className: 'muted' }, preview.label + ' · ' + t('已选 ', 'Selected ') + chosen.length + '/' + preview.rows.length),
          preview.rows.map(r => h('div', { className: 'entry', key: r.index }, h('label', { className: 'choose' }, h('input', { type: 'checkbox', checked: chosen.includes(r.index), disabled: locked || !!r.error || !!r.duplicate, 'aria-label': t('保存预览条目 ', 'Save preview entry ') + (r.index + 1), onChange: () => toggle(chosen, r.index, setChosen) }), h('span', null, h('strong', null, (r.index + 1) + '. ' + (r.work?.title || r.work?.doi || r.key)), r.work && h('div', { className: 'muted' }, [authors(r.work), r.work.year || '', r.work.doi].filter(Boolean).join(' · ')), r.duplicate && h('span', { className: 'tag warn' }, r.duplicate === 'library' ? t('DOI 已在库中，跳过', 'DOI already saved; skipped') : t('同批 DOI 重复，跳过', 'Repeated DOI in this batch; skipped')), r.candidate && h('span', { className: 'tag warn' }, t('可能重复，请核对后决定', 'Possible duplicate; review before selecting')), r.warnings.map(w => h('span', { key: w, className: 'tag warn' }, warning(w))), r.error && h('p', { className: 'notice error' }, t(r.error, r.errorEn || 'Invalid reference. Check the original input.')))))),
          h('div', { className: 'bar' }, h('button', { className: 'primary', disabled: locked || conflict || !chosen.length, onClick: () => perform(save) }, t('保存所选 ', 'Save selected ') + chosen.length), h('button', { disabled: locked, onClick: () => { setPreview(null); setChosen([]); } }, t('返回输入', 'Back to input'))))),
      h('div', null, h('div', { className: 'card' }, h('h3', null, t('2. 文献库', '2. Library')), h('div', { className: 'bar' }, h('span', null, library.entries.length + t(' 条 · 修订 ', ' entries · revision ') + library.revision), h('button', { disabled: locked, onClick: () => perform(refresh) }, t('刷新文献库', 'Refresh library'))),
        library.entries.length ? h(React.Fragment, null, h('label', { htmlFor: 'cite-search' }, t('搜索已保存文献', 'Search saved entries')), h('input', { id: 'cite-search', value: search, onChange: e => { setSearch(e.target.value); setLimit(50); } }),
          h('div', { className: 'bar' }, h('button', { disabled: locked || !visible.length, onClick: () => setSelected(visible.slice(0, 100).map(e => e.id)) }, t('选择当前可见项（最多 100）', 'Select visible (up to 100)')), h('button', { disabled: locked || !selected.length, onClick: () => setSelected([]) }, t('清空选择', 'Clear selection')), h('span', { className: 'muted' }, t('已选 ', 'Selected ') + selected.length)),
          visible.map(e => h('div', { className: 'entry', key: e.id }, h('label', { className: 'choose' }, h('input', { type: 'checkbox', checked: selected.includes(e.id), disabled: locked || selected.length >= 100 && !selected.includes(e.id), 'aria-label': t('选择文献 ', 'Select entry ') + (e.work.title || e.work.doi || e.id), onChange: () => toggle(selected, e.id, setSelected) }), h('span', null, h('strong', null, e.work.title || e.work.doi || t('无标题', 'Untitled')), h('div', { className: 'muted' }, [authors(e.work), e.work.year || '', e.work.doi].filter(Boolean).join(' · ')), e.warnings.map(w => h('span', { className: 'tag warn', key: w }, warning(w))))),
            h('details', null, h('summary', null, t('元数据与来源', 'Metadata and sources')), h('dl', null, ['containerTitle','publisher','volume','issue','page','url','isbn'].filter(key => e.work[key]).flatMap(key => [h('dt', { key: key + '-dt' }, fieldName(key)), h('dd', { key: key + '-dd' }, e.work[key])])), h('p', { className: 'muted' }, t('导入来源：', 'Imported from: ') + e.sourceIds.map(id => library.sources.find(s => s.id === id)?.label || id).join(', ')), e.crossref && h('p', { className: 'muted' }, 'Crossref · ' + new Date(e.crossref.fetchedAt).toLocaleString()), e.crossref?.conflicts?.length > 0 && h('div', { className: 'notice error' }, h('strong', null, t('有差异，已保留本地值', 'Differences found; local values retained')), e.crossref.conflicts.map(c => h('div', { key: c.field }, h('strong', null, fieldName(c.field)), h('p', null, t('本地：', 'Local: ') + valueText(c.local)), h('p', null, 'Crossref: ' + valueText(c.crossref))))), h('button', { onClick: () => setActiveId(e.id) }, t('预览这条引文', 'Preview this reference'))))),
          h('p', { className: 'muted' }, t('显示 ', 'Showing ') + visible.length + '/' + filtered.length), visible.length < filtered.length && h('button', { onClick: () => setLimit(n => n + 50) }, t('再显示 50 条', 'Show 50 more'))) : h('p', { className: 'muted' }, t('文献库为空。先预览输入，再保存选择的文献。', 'Your library is empty. Preview input, then save the entries you choose.')),
        h('div', { className: 'bar' }, h('button', { className: 'primary', disabled: locked || !selected.length, onClick: () => perform(async () => { setJob(await api({ action: 'enrich', ids: selected, revision: library.revision })); }) }, t('从 Crossref 在线补全所选项', 'Fill selected entries from Crossref (online)'))), h('p', { className: 'muted' }, t('每次最多 100 条，必须有 DOI。只补空字段；冲突会保留本地值并列出差异。失败可以重新选择后重试。', 'Up to 100 entries with a DOI per job. Only empty fields are filled. Conflicts retain local values and show differences. Select failed entries to retry.'))),
        job && h('div', { className: job.state === 'failed' ? 'card notice error' : 'card', role: job.state === 'failed' ? 'alert' : 'status' }, h('h3', null, t('补全进度', 'Enrichment progress')), h('progress', { max: job.total, value: job.completed }), h('p', null, ({ running: t('查询中', 'Looking up'), done: t('已完成', 'Completed'), failed: t('未保存本次补全', 'Enrichment was not saved'), cancelled: t('已取消，原文献保留', 'Cancelled; saved entries preserved') }[job.state]) + ' · ' + job.completed + '/' + job.total), job.state === 'done' && h('p', null, t('已检查并保存 ', 'Entries checked and saved: ') + job.saved + t(' 条；失败 ', '; failed: ') + job.results.filter(r => !r.ok).length), job.message && h('p', { className: 'notice error' }, t(job.message, job.messageEn || 'The job could not be completed; saved entries are preserved.')), running && h('button', { disabled: busy, onClick: () => perform(async () => { await api({ action: 'cancel', job: job.id }); }) }, t('取消本次补全', 'Cancel enrichment')), h('details', null, h('summary', null, t('查看每条结果', 'Show individual results')), job.results.map(r => h('div', { className: 'entry', key: r.id }, h('strong', null, r.doi || t('没有 DOI', 'No DOI')), h('p', null, r.ok ? t('补全字段：', 'Fields filled: ') + (r.filled.length ? r.filled.map(fieldName).join(', ') : t('无需补全', 'none needed')) : t(r.error, r.errorEn || 'Lookup failed. Check the DOI or retry.')), r.conflicts?.length > 0 && h('p', { className: 'warn' }, t('有 ', 'Differences: ') + r.conflicts.length + t(' 项差异；请查看文献详情。', '; see entry details.')))))),
        h('div', { className: 'card' }, h('h3', null, t('3. 引文与下载', '3. References and downloads')), h('label', { htmlFor: 'cite-style' }, t('引文格式（基本格式）', 'Citation style (basic)')), h('select', { id: 'cite-style', value: style, onChange: e => setStyle(e.target.value) }, ['gb-t-7714','apa','mla','chicago'].map((value, i) => h('option', { value, key: value }, ['GB/T 7714','APA','MLA','Chicago'][i]))), citation && h('pre', { 'aria-label': t('引文预览', 'Reference preview') }, citation), h('p', { className: 'muted' }, t('沿用原插件的四种基本格式；提交论文前请核对学校或期刊要求。上方可预览单条引文。', 'Uses the existing four basic styles. Check your institution or journal requirements before submission. Use an entry above to preview its reference.')),
          h('p', null, selected.length ? t('下载范围：所选 ', 'Download scope: selected ') + selected.length : t('下载范围：全部文献', 'Download scope: entire library')), h('div', { className: 'bar' }, downloadLink('bibtex', '下载 BibTeX', 'Download BibTeX'), downloadLink('references', '下载参考文献文本', 'Download reference text'), downloadLink('backup', '完整备份（含原始来源）', 'Full backup (with original sources)')),
          h('p', { className: 'muted' }, t('完整备份始终包含全库及原始输入，不受选择范围影响。导出 BibTeX 使用互不重复的引用键；保留的原始来源用于核对未映射字段。', 'Full backup always includes the entire library and original input. BibTeX exports use unique citation keys. Original sources preserve fields that are not mapped into this workbench.'))))));
  }
  function apply(ctx) { let locale; try { locale = ctx.get?.('locale') || ctx.locale; } catch {} ctx.slots.inject('settings.section', () => ctx.slots.register({ name: 'settings.section', id: 'dsh-cite', order: 64, label: () => 'Cite', inject: () => ({ locale }) }, Workbench)); }
  return { inject: ['slots', 'locale'], apply };
} });
